id: I0C8CA8DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:39:57+00:00'
last_modified: '2022-06-08T09:40:50.515709+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4852
  title: གཞོན་ནུ་བློ་གྲོས་ཀྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    BDA4:
      image_group_id: I1KG5118
      title: ''
      total_pages: 159
      order: 1
      base_file: BDA4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
