id: P009249
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-19 19:29:56.731469
source_metadata:
  id: bdr:W1KG4852
  title: གཞོན་ནུ་བློ་གྲོས་ཀྱི་རྣམ་ཐར
  author: ''
  volumes:
    9b52b5393ee0434a853d975123e1088e:
      image_group_id: I1KG5118
      title: ''
      volume_number: 1
      total_pages: 159
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
